<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import { Head, router, useForm } from '@inertiajs/vue3';
const props = defineProps({sites:Array});
const siteForm=useForm({name:'',address:'',criticality_tier:'standard'});
const areaForms={};
const areaForm=(id)=>areaForms[id] ||= useForm({name:'',description:''});
const addSite=()=>siteForm.post(route('sites.store'),{onSuccess:()=>siteForm.reset()});
const addArea=(site)=>areaForm(site.id).post(route('process-areas.store',site.id),{onSuccess:()=>areaForm(site.id).reset()});
const remove=(name,url)=>{if(confirm(`Remove ${name}?`)) router.delete(url)};
</script>
<template><Head title="Sites"/><AuthenticatedLayout><template #header><div><h1 class="text-xl font-semibold">Sites and process areas</h1><p class="mt-1 text-sm text-slate-500">Organize assets the way operators know the plant.</p></div></template><div class="mx-auto grid max-w-6xl gap-6 px-4 py-8 lg:grid-cols-[340px_1fr]"><aside><form @submit.prevent="addSite" class="space-y-4 rounded-xl border bg-white p-5 shadow-sm"><h2 class="font-semibold">Add a site</h2><div><label class="text-sm font-medium">Site name *</label><input v-model="siteForm.name" required class="mt-1 w-full rounded-lg border-slate-300"/><InputError :message="siteForm.errors.name"/></div><div><label class="text-sm font-medium">Address</label><textarea v-model="siteForm.address" class="mt-1 w-full rounded-lg border-slate-300"></textarea></div><div><label class="text-sm font-medium">Criticality</label><select v-model="siteForm.criticality_tier" class="mt-1 w-full rounded-lg border-slate-300"><option value="standard">Standard</option><option value="important">Important</option><option value="critical">Critical</option></select></div><button class="w-full rounded-lg bg-teal-700 px-4 py-2 text-sm font-semibold text-white">Add site</button></form></aside><section class="space-y-5"><div v-for="site in sites" :key="site.id" class="rounded-xl border bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="text-lg font-semibold">{{site.name}}</h2><p class="text-sm text-slate-500">{{site.address||'No address recorded'}} · {{site.assets_count}} assets</p></div><button @click="remove(site.name,route('sites.destroy',site.id))" class="text-sm text-red-700">Remove</button></div><div class="mt-5 border-t pt-4"><h3 class="text-sm font-semibold">Process areas</h3><div class="mt-2 flex flex-wrap gap-2"><span v-for="area in site.process_areas" :key="area.id" class="inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-sm">{{area.name}}<button @click="remove(area.name,route('process-areas.destroy',area.id))" aria-label="Remove process area" class="text-slate-400 hover:text-red-700">×</button></span><span v-if="!site.process_areas.length" class="text-sm text-slate-500">None yet</span></div><form @submit.prevent="addArea(site)" class="mt-4 flex gap-2"><input v-model="areaForm(site.id).name" required placeholder="e.g. Filtration" class="min-w-0 flex-1 rounded-lg border-slate-300 text-sm"/><button class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium">Add area</button></form></div></div><div v-if="!sites.length" class="rounded-xl border border-dashed p-10 text-center text-slate-500">Add your first facility to start building the inventory.</div></section></div></AuthenticatedLayout></template>
