<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, router, useForm, usePage } from '@inertiajs/vue3';
const props = defineProps({ agents: Array });
const page = usePage();
const form = useForm({ name: '' });
const enroll = () => form.post(route('agents.store'), { preserveScroll: true, onSuccess: () => form.reset() });
const revoke = (agent) => { if (confirm(`Revoke ${agent.name}? It will stop reporting immediately.`)) router.delete(route('agents.destroy', agent.id), { preserveScroll: true }); };
const copy = () => navigator.clipboard.writeText(page.props.flash.agent_token);
</script>
<template><Head title="Local agents" /><AuthenticatedLayout><template #header><div><h1 class="text-2xl font-semibold">Local monitoring agents</h1><p class="text-sm text-slate-500">Collectors that report from inside utility networks.</p></div></template><div class="mx-auto grid max-w-6xl gap-6 px-4 py-8 lg:grid-cols-[3fr_2fr]"><section class="rounded-xl border bg-white p-6 shadow-sm"><h2 class="font-semibold">Enrolled agents</h2><div class="mt-4 divide-y"><div v-for="agent in agents" :key="agent.id" class="flex items-start justify-between gap-4 py-4"><div><div class="flex items-center gap-2"><p class="font-medium">{{ agent.name }}</p><span class="rounded-full px-2 py-0.5 text-xs font-semibold" :class="agent.is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-600'">{{ agent.is_active ? 'Active' : 'Revoked' }}</span></div><p class="mt-1 text-xs text-slate-500">Last report: {{ agent.last_seen_at ? new Date(agent.last_seen_at).toLocaleString() : 'Never' }}<span v-if="agent.version"> / v{{ agent.version }}</span></p></div><button v-if="agent.is_active" @click="revoke(agent)" class="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-700">Revoke</button></div><p v-if="!agents.length" class="py-8 text-center text-sm text-slate-500">No local agents enrolled.</p></div></section><aside class="space-y-5"><div v-if="$page.props.flash.agent_token" class="rounded-xl border border-amber-300 bg-amber-50 p-5 shadow-sm"><h2 class="font-semibold">Copy this token now</h2><p class="mt-1 text-xs text-amber-800">For security, it will not be shown again.</p><code class="mt-3 block break-all rounded bg-white p-3 text-xs">{{ $page.props.flash.agent_token }}</code><button @click="copy" class="mt-3 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Copy token</button></div><form @submit.prevent="enroll" class="rounded-xl border bg-white p-5 shadow-sm"><h2 class="font-semibold">Enroll an agent</h2><label class="mt-4 block text-sm font-medium">Agent name</label><input v-model="form.name" required class="mt-1 w-full rounded-lg border-slate-300" placeholder="North Plant collector" /><button class="mt-4 w-full rounded-lg bg-teal-700 px-4 py-2 text-sm font-semibold text-white">Create one-time token</button></form><div class="rounded-xl border bg-white p-5 text-sm shadow-sm"><h2 class="font-semibold">Installation</h2><ol class="mt-3 list-decimal space-y-2 pl-5 text-slate-600"><li>Copy the <code>agent/</code> folder to a monitored workstation.</li><li>Copy <code>config.example.json</code> to <code>config.json</code>.</li><li>Set the dashboard URL and one-time token.</li><li>Schedule <code>php oteim-agent.php</code> every five minutes.</li></ol></div></aside></div></AuthenticatedLayout></template>
