<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import { computed } from 'vue';

const props = defineProps({ asset: { type: Object, default: null }, sites: Array });
const form = useForm({ site_id: props.asset?.site_id || '', process_area_id: props.asset?.process_area_id || '', name: props.asset?.name || '', asset_type: props.asset?.asset_type || 'plc', vendor: props.asset?.vendor || '', model: props.asset?.model || '', firmware_version: props.asset?.firmware_version || '', internal_ip: props.asset?.internal_ip || '', external_ip: props.asset?.external_ip || '', data_source_type: props.asset?.data_source_type || 'manual', criticality: props.asset?.criticality || 'medium', notes: props.asset?.notes || '' });
const areas = computed(() => props.sites.find(site => Number(site.id) === Number(form.site_id))?.process_areas || []);
const submit = () => props.asset ? form.put(route('assets.update', props.asset.id)) : form.post(route('assets.store'));
const fields = [['name','Device name'],['vendor','Vendor'],['model','Model'],['firmware_version','Firmware version'],['internal_ip','Internal IP address'],['external_ip','External IP address']];
</script>
<template><Head :title="asset ? 'Edit asset' : 'Add asset'"/><AuthenticatedLayout><template #header><h1 class="text-xl font-semibold text-slate-900">{{ asset ? 'Edit asset' : 'Add asset' }}</h1></template><div class="mx-auto max-w-3xl px-4 py-8"><form @submit.prevent="submit" class="space-y-6 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div class="grid gap-5 sm:grid-cols-2"><div v-for="([key,label]) in fields" :key="key"><label :for="key" class="mb-1 block text-sm font-medium text-slate-700">{{ label }}<span v-if="key==='name'"> *</span></label><input :id="key" v-model="form[key]" :required="key==='name'" class="w-full rounded-lg border-slate-300"/><InputError class="mt-1" :message="form.errors[key]"/></div><div><label class="mb-1 block text-sm font-medium">Site *</label><select v-model="form.site_id" required class="w-full rounded-lg border-slate-300"><option value="" disabled>Select site</option><option v-for="site in sites" :value="site.id" :key="site.id">{{ site.name }}</option></select><InputError class="mt-1" :message="form.errors.site_id"/></div><div><label class="mb-1 block text-sm font-medium">Process area</label><select v-model="form.process_area_id" class="w-full rounded-lg border-slate-300"><option value="">None</option><option v-for="area in areas" :value="area.id" :key="area.id">{{ area.name }}</option></select></div><div><label class="mb-1 block text-sm font-medium">Asset type *</label><select v-model="form.asset_type" class="w-full rounded-lg border-slate-300"><option v-for="item in ['plc','rtu','hmi','historian','switch','other']" :key="item" :value="item">{{ item.toUpperCase() }}</option></select></div><div><label class="mb-1 block text-sm font-medium">Monitoring source *</label><select v-model="form.data_source_type" class="w-full rounded-lg border-slate-300"><option value="manual">Manual</option><option value="cloud_scan">Cloud scan</option><option value="agent">Local agent</option></select></div><div><label class="mb-1 block text-sm font-medium">Criticality *</label><select v-model="form.criticality" class="w-full rounded-lg border-slate-300"><option v-for="item in ['low','medium','high','critical']" :value="item" :key="item">{{ item }}</option></select></div></div><div><label class="mb-1 block text-sm font-medium">Notes and compensating controls</label><textarea v-model="form.notes" rows="5" class="w-full rounded-lg border-slate-300"></textarea></div><div class="flex justify-end gap-3"><Link :href="asset ? route('assets.show', asset.id) : route('assets.index')" class="px-4 py-2 text-sm">Cancel</Link><button :disabled="form.processing" class="rounded-lg bg-teal-700 px-5 py-2 text-sm font-semibold text-white">{{ asset ? 'Save changes' : 'Add asset' }}</button></div></form></div></AuthenticatedLayout></template>
