<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';

const props = defineProps({ asset: Object });
const remove = () => { if (confirm(`Remove ${props.asset.name}?`)) router.delete(route('assets.destroy', props.asset.id)); };
const attestation = useForm({ result: props.asset.is_internet_facing ? 'exposed' : 'not_exposed', note: '', recheck_at: '' });
const recordExposure = () => attestation.post(route('assets.exposure.manual', props.asset.id), { preserveScroll: true, onSuccess: () => attestation.reset('note') });
const integrity = useForm({ internal_ip: props.asset.internal_ip || '', fingerprint: '', auth_success: true, firmware_version: props.asset.firmware_version || '', config_checksum: '', note: '' });
const recordIntegrity = () => integrity.post(route('assets.integrity.manual', props.asset.id), { preserveScroll: true, onSuccess: () => integrity.reset('note') });
const acceptChange = (event) => {
    const note = prompt('Why is this a legitimate change? This note will be kept in the audit log.');
    if (note) router.patch(route('integrity-events.accept', event.id), { note }, { preserveScroll: true });
};
const details = [['Vendor', props.asset.vendor], ['Model', props.asset.model], ['Firmware', props.asset.firmware_version], ['Internal IP', props.asset.internal_ip], ['External IP', props.asset.external_ip], ['Monitoring source', props.asset.data_source_type?.replace('_', ' ')], ['Criticality', props.asset.criticality]];
</script>

<template>
    <Head :title="asset.name" />
    <AuthenticatedLayout>
        <template #header><div class="flex items-center justify-between"><div><p class="text-sm font-medium uppercase tracking-wide text-teal-700">{{ asset.asset_type }}</p><h1 class="text-2xl font-semibold">{{ asset.name }}</h1></div><div v-if="['admin','operator'].includes($page.props.auth.role)" class="flex gap-2"><Link :href="route('assets.edit', asset.id)" class="rounded-lg border px-4 py-2 text-sm font-medium">Edit</Link><button @click="remove" class="rounded-lg border border-red-200 px-4 py-2 text-sm text-red-700">Remove</button></div></div></template>
        <div class="mx-auto grid max-w-6xl gap-6 px-4 py-8 lg:grid-cols-[3fr_2fr]">
            <div class="space-y-6">
                <section class="rounded-xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Device details</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div v-for="([label,value]) in details" :key="label"><dt class="text-xs font-semibold uppercase text-slate-500">{{ label }}</dt><dd class="mt-1 capitalize">{{ value || 'Not recorded' }}</dd></div></dl><div class="mt-6 border-t pt-5"><h3 class="text-sm font-semibold">Notes and compensating controls</h3><p class="mt-2 whitespace-pre-wrap text-sm text-slate-600">{{ asset.notes || 'None recorded.' }}</p></div></section>
                <section class="rounded-xl border bg-white p-6 shadow-sm"><div class="flex justify-between"><h2 class="text-lg font-semibold">Relevant advisories</h2><Link :href="route('advisories.index')" class="text-sm font-medium text-teal-700">View all</Link></div><div class="mt-4 divide-y"><div v-for="match in asset.advisory_matches" :key="match.id" class="py-3"><div class="flex items-start justify-between gap-3"><Link :href="route('advisories.show', match.advisory.id)" class="font-medium hover:text-teal-700">{{ match.advisory.title }}</Link><span class="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-semibold capitalize">{{ match.status.replace('_', ' ') }}</span></div><p class="mt-1 text-xs uppercase text-slate-500">{{ match.advisory.external_id }} / {{ match.advisory.severity }}</p></div><p v-if="!asset.advisory_matches.length" class="py-7 text-center text-sm text-slate-500">No advisories currently match this device.</p></div></section>
                <section class="rounded-xl border bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-lg font-semibold">Integrity changes</h2><span v-if="asset.baseline" class="text-xs font-medium text-emerald-700">Baseline active</span></div><p class="mt-1 text-sm text-slate-500">Readings are compared with the last accepted baseline. Authentication failures are symptoms to investigate, not proof that a password changed.</p><div class="mt-4 divide-y"><div v-for="event in asset.integrity_events" :key="event.id" class="py-4"><div class="flex items-start justify-between gap-3"><div><p class="font-medium">{{ event.notes }}</p><p class="mt-1 text-xs uppercase text-slate-500">{{ event.severity }} / {{ new Date(event.detected_at).toLocaleString() }}</p></div><button v-if="!event.acknowledged_at" @click="acceptChange(event)" class="shrink-0 rounded-lg border px-3 py-1.5 text-xs font-semibold text-teal-700">Accept change</button><span v-else class="text-xs font-medium text-emerald-700">Accepted</span></div></div><p v-if="!asset.integrity_events.length" class="py-8 text-center text-sm text-slate-500">No integrity drift detected.</p></div></section>
                <section class="rounded-xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Exposure history</h2><div class="mt-4 divide-y"><div v-for="scan in asset.exposure_scans" :key="scan.id" class="py-3"><div class="flex justify-between gap-3"><span class="font-medium" :class="scan.result === 'exposed' ? 'text-red-700' : 'text-slate-800'">{{ scan.result === 'exposed' ? 'Reachable from the internet' : scan.result.replace('_', ' ') }}</span><time class="text-xs text-slate-500">{{ new Date(scan.scanned_at).toLocaleString() }}</time></div><p class="mt-1 text-xs capitalize text-slate-500">{{ scan.method }} check<span v-if="scan.note"> / {{ scan.note }}</span></p></div><p v-if="!asset.exposure_scans.length" class="py-8 text-center text-sm text-slate-500">No exposure checks yet.</p></div></section>
            </div>
            <aside class="space-y-5">
                <div class="rounded-xl border p-5 shadow-sm" :class="asset.is_internet_facing ? 'border-red-300 bg-red-50' : 'bg-white'"><p class="text-xs font-semibold uppercase text-slate-500">Current exposure</p><p class="mt-2 text-lg font-semibold" :class="asset.is_internet_facing ? 'text-red-700' : 'text-emerald-700'">{{ asset.is_internet_facing ? 'This device can currently be reached from the internet' : 'Not known to be internet-reachable' }}</p></div>
                <form v-if="['admin','operator'].includes($page.props.auth.role)" @submit.prevent="recordIntegrity" class="rounded-xl border bg-white p-5 shadow-sm"><h2 class="font-semibold">Record integrity reading</h2><p class="mt-1 text-xs text-slate-500">The first reading establishes the accepted baseline.</p><label class="mt-4 block text-sm font-medium">Internal IP</label><input v-model="integrity.internal_ip" class="mt-1 w-full rounded-lg border-slate-300" /><label class="mt-3 block text-sm font-medium">Firmware version</label><input v-model="integrity.firmware_version" class="mt-1 w-full rounded-lg border-slate-300" /><label class="mt-3 block text-sm font-medium">Device fingerprint</label><input v-model="integrity.fingerprint" class="mt-1 w-full rounded-lg border-slate-300" placeholder="Serial, certificate, or agent ID" /><label class="mt-3 block text-sm font-medium">Configuration checksum</label><input v-model="integrity.config_checksum" class="mt-1 w-full rounded-lg border-slate-300" /><label class="mt-3 flex items-center gap-2 text-sm"><input v-model="integrity.auth_success" type="checkbox" class="rounded border-slate-300 text-teal-700" /> Monitoring login succeeds</label><label class="mt-3 block text-sm font-medium">Operator note</label><textarea v-model="integrity.note" rows="2" class="mt-1 w-full rounded-lg border-slate-300"></textarea><InputError :message="integrity.errors.snapshot" /><button class="mt-4 w-full rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Save integrity reading</button></form>
                <form v-if="['admin','operator'].includes($page.props.auth.role)" @submit.prevent="recordExposure" class="rounded-xl border bg-white p-5 shadow-sm"><h2 class="font-semibold">Record a manual exposure check</h2><p class="mt-1 text-xs text-slate-500">Use this when an operator has verified the device or firewall state.</p><label class="mt-4 block text-sm font-medium">Result</label><select v-model="attestation.result" class="mt-1 w-full rounded-lg border-slate-300"><option value="not_exposed">Not reachable from internet</option><option value="exposed">Reachable from internet</option><option value="unknown">Could not verify</option></select><label class="mt-4 block text-sm font-medium">Verification note *</label><textarea v-model="attestation.note" required rows="3" class="mt-1 w-full rounded-lg border-slate-300" placeholder="What was checked and by whom?"></textarea><InputError :message="attestation.errors.note" /><label class="mt-4 block text-sm font-medium">Check again on</label><input v-model="attestation.recheck_at" type="date" class="mt-1 w-full rounded-lg border-slate-300" /><InputError :message="attestation.errors.recheck_at" /><button class="mt-4 w-full rounded-lg bg-teal-700 px-4 py-2 text-sm font-semibold text-white">Save exposure check</button></form>
            </aside>
        </div>
    </AuthenticatedLayout>
</template>
